name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Aplication
        run: npm run build

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: http://149.56.205.234
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v3
      - name: Vps Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDz --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
